version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_todo
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: vinicius
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vinicius"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: todo_api_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/todo_db
      SPRING_DATASOURCE_USERNAME: vinicius
      SPRING_DATASOURCE_PASSWORD: 123456

volumes:
  postgres-data:
